[versions]
avro = "1.12.2"
jackson = "3.1.5"
jmh = "1.37"
junit = "6.0.3"
maven-publish = "0.37.0"
spring-boot = "4.1.1"

[libraries]
jmh-core = { module = "org.openjdk.jmh:jmh-core", version.ref = "jmh" }
jmh-generator = { module = "org.openjdk.jmh:jmh-generator-annprocess", version.ref = "jmh" }
avro = { module = "org.apache.avro:avro", version.ref = "avro" }
avro-compiler = { module = "org.apache.avro:avro-compiler", version.ref = "avro" }
jackson-databind = { module = "tools.jackson.core:jackson-databind", version.ref = "jackson" }
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter", version.ref = "junit" }
spring-boot-dependencies = { module = "org.springframework.boot:spring-boot-dependencies", version.ref = "spring-boot" }
spring-boot-autoconfigure = { module = "org.springframework.boot:spring-boot-autoconfigure", version.ref = "spring-boot" }

[plugins]
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "maven-publish" }
spring-boot = { id = "org.springframework.boot", version.ref = "spring-boot" }
